config/routes.rb
Rails.application.routes.draw do
  resources :orders
  root 'orders#index'
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :order

end

app/models/order.rb
class Order < ApplicationRecord
  CCARD_ISSUER = [["master", "Master Card"], ["visa", "Visa"]]
  has_many :messages, dependent: :destroy

  enum payment_method: [:sepa, :amazon, :paypal, :credit_card]

  attribute :auto_translate, :boolean, default: true
  attribute :iban, :string
  attribute :bic, :string
  attribute :cc_owner, :string
  attribute :cc_issuer, :string
  attribute :cc_number, :string
  attribute :cc_checksum, :integer
  attribute :cc_valid_till_month, :integer
  attribute :cc_valid_till_year, :integer

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    @order = Order.new
    @order.messages << Message.new if @order.messages.empty?
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    title Gift
    meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = javascript_pack_tag 'application'
    = stylesheet_pack_tag "application"
  body
    nav.white[role="navigation"]
      .nav-wrapper.container
        a#logo-container.brand-logo[href="#"]
          | Logo
        ul.right.hide-on-med-and-down
          li
            a[href="#"]
              | Navbar Link
        ul#nav-mobile.sidenav
          li
            a[href="#"]
              | Navbar Link
        a.sidenav-trigger[href="#" data-target="nav-mobile"]
          i.material-icons
            | menu

    = yield

    footer.page-footer.teal
      .container
        .row
          .col.l6.s12
            h5.white-text
              | About Us
            p.grey-text.text-lighten-4
              | Lengthy description of who we are and why we do this?
          .col.l3.s12
            h5.white-text
              | Settings
            ul
              li
                a.white-text[href="#!"]
                  | Link 1
              li
                a.white-text[href="#!"]
                  | Link 2
              li
                a.white-text[href="#!"]
                  | Link 3
              li
                a.white-text[href="#!"]
                  | Link 4
          .col.l3.s12
            h5.white-text
              | Connect
            ul
              li
                a.white-text[href="#!"]
                  | Link 1
              li
                a.white-text[href="#!"]
                  | Link 2
              li
                a.white-text[href="#!"]
                  | Link 3
              li
                a.white-text[href="#!"]
                  | Link 4
      .footer-copyright
        .container
          ' Made with
          i.fas.fa-heart.red-text>
          ' in
          a.brown-text.text-lighten-3 href="https://walldorf.de" Walldorf

app/views/orders/_form.html.slim
= form_for @order, html: {data: {controller: "form", packages: @order.packages || 1}} do |f|
  - if @order.errors.any?
    #error_explanation
      h2 = "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      ul
        - @order.errors.full_messages.each do |message|
          li = message
  .row
    .col.s2.offset-s2
      h4 Ich möchte
    .col.s1
      a.btn-floating.waves-effect.waves-light.blue data-action="click->form#less"
        i.fa.fa-minus
    .col.s1
      input data-target="form.packages" value="42" type="number" min=1
    .col.s1
      a.btn-floating.waves-effect.waves-light.green data-action="click->form#more"
        i.fa.fa-plus
    .col.s4
      h4 Päckchen versenden
  .row
    .col.s1.offset-s10
      h2 data-target="form.sum"
    .col.s1
      h2 €
  .row
    .col.s12
      h3 Persönliche Botschaft
  .row
    .col.s8.offset-s2
      = f.fields_for :messages do |m|
        .input-field
          = m.label :text
          = m.text_area :text, rows: 4, cols: 4, size: "4x4", class: "materialize-textarea", data: {target: "form.message"}
    .col.s2.input-field
      = f.label :auto_translate
        = f.check_box :auto_translate
        span Automatisch übersetzen

  .row
    .input-field.col.s12
      i.material-icons.fa.fa-envelope.prefix
      = f.label :email
      = f.text_field :email
  .row
    .col.s6.input-field
      i.material-icons.fa.fa-user.prefix
      = f.label :firstname
      = f.text_field :firstname
    .col.s6.input-field
      i.material-icons.fa.fa-user-circle.prefix
      = f.label :lastname
      = f.text_field :lastname
    .col.s4.input-field
      i.material-icons.fa.fa-asterisk.prefix
      = f.label :postcode
      = f.number_field :postcode
    .col.s8.input-field
      i.material-icons.fa.fa-home.prefix
      = f.label :city
      = f.number_field :city

  h4 Zahlungsart
  .row
    .col.s10.offset-s1
      ul.tabs data-target="form.payment"
        li.tab.col.s3:a href="#sepa"
          = image_pack_tag "images/SepaLogoEN.jpg", size: '130x47', alt: 'SEPA Lastschrift'
        li.tab.col.s3:a href="#amazon"
          i.fab.fa-amazon-pay.fa-4x.blue-text.text-darken-4
        li.tab.col.s3:a href="#paypal"
          i.fab.fa-paypal.fa-4x.blue-text.text-darken-4
        li.tab.col.s3:a href="#creditcard"
          i.far.fa-credit-card.fa-4x.blue-text.text-darken-4
    #sepa.col.s10.offset-s1
      .row
        .col.s6.input-field.offset-s3
          = f.label :iban
          = f.text_field :iban
        .col.s6.input-field.offset-s3
          = f.label :bic
          = f.text_field :bic
    #amazon.col.s12
      h3 Sie werden auf Amazon Payment weitergeleitet.
    #paypal.col.s12
      h3 Sie werden auf Paypal weitergeleitet.
    #creditcard.col.s12
      h3 CreditCars Payment
      .row
        .col.s6.input-field
          = f.label :cc_issuer
          = f.collection_select :cc_issuer, Order::CCARD_ISSUER, :first, :second, {}, {data: {target: "form.ccIssuer"}}
        .col.s6.input-field
          = f.label :cc_owner
          = f.text_field :cc_owner
        .col.s8.input-field
          = f.label :cc_number
          = f.text_field :cc_number
        .col.s3.input-field
          = f.label :cc_checksum
          = f.text_field :cc_checksum
        .col.s3.input-field
          = f.label :cc_valid_till_month
          = f.text_field :cc_valid_till_month
        .col.s3.input-field
          = f.label :cc_valid_till_year
          = f.text_field :cc_valid_till_year
  .right-align
    = f.submit "Kostenpflichtig Spenden", class: "waves-effect waves-light btn green white-text"

app/views/orders/edit.html.slim
h1 Editing order

== render 'form'

=> link_to 'Show', @order
'|
=< link_to 'Back', orders_path

app/views/orders/index.html.slim
#index-banner.parallax-container data-controller="order"
  .section.no-pad-bot
    .container
      br
      br
      h1.header.center.teal-text.text-lighten-2
        | Lorem Ipsum
      .row.center
        h5.header.col.s12.light
          | A catchy subtitle that engages
          b< everyone

      .row.center
        a.btn-large.waves-effect.waves-light.teal.lighten-1 data-action="click->order#scroll"
          | Donate Now
  .parallax
    = image_pack_tag "images/raw2.jpeg"
.container
  .section
    .row
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.fas.fa-stroopwafel
          h5.center
            | Advantage number 1
          p.light
            | Maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac,
            | gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum
            | primis in faucibus orci luctus et ultrices posuere cubilia Curae;
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.fas.fa-people-carry
          h5.center
            | Advantage number 2
          p.light
            | Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et
            | pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl
            | maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac,
      .col.s12.m4
        .icon-block
          h2.center.brown-text
            i.fas.fa-users
          h5.center
            | Advantage number 3
          p.light
            | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat.
            | Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros.
            | Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light
          | Another phrase just to show off
  .parallax
    = image_pack_tag "images/raw2.jpeg"
.container
  .section
    .row
      .col.s12.center
        h3
          i.mdi-content-send.brown-text
        h4
          | You can do it
        p.left-align.light
          | Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque id nunc nec volutpat.
          | Etiam pellentesque tristique arcu, non consequat magna fermentum ac. Cras ut ultricies eros.
          | Maecenas eros justo, ullamcorper a sapien id, viverra ultrices eros. Morbi sem neque, posuere et
          | pretium eget, bibendum sollicitudin lacus. Aliquam eleifend sollicitudin diam, eu mattis nisl
          | maximus sed. Nulla imperdiet semper molestie. Morbi massa odio, condimentum sed ipsum ac,
          | gravida ultrices erat. Nullam eget dignissim mauris, non tristique erat. Vestibulum ante ipsum
          | primis in faucibus orci luctus et ultrices posuere cubilia Curae;
.parallax-container.valign-wrapper
  .section.no-pad-bot
    .container
      .row.center
        h5.header.col.s12.light
          |
  .parallax
    = image_pack_tag "images/raw3.jpeg"
.container
  .section
    .row
      .col.s12.center#form

        h1 Donate Now

        = render partial: "form"

app/views/orders/new.html.slim
h1 New order

== render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.slim
p#notice = notice

p
  strong Email:
  = @order.email

=> link_to 'Edit', edit_order_path(@order)
'|
=< link_to 'Back', orders_path